imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    cache_type: file_system

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    number_format:
        thousands_separator: ' '

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_cache:
    providers:
        markdown_cache:
            type: %cache_type%
            file_system:
                directory: %kernel.cache_dir%/markdown_cache

stof_doctrine_extensions:
    default_locale:  "%locale%"
    orm:
        default:
            timestampable: true
            blameable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.noop

sonata_user:
    security_acl: false
    manager_type: orm
    class:
         user: Application\Sonata\UserBundle\Entity\User
         group: Application\Sonata\UserBundle\Entity\Group

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:
        sonata.admin.block.stats:
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.user.block.menu:


sonata_admin:
    title: Tinkoff Store
    title_logo: "/images/logo.png"
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            -
                position: top
                type: sonata.block.service.text
                settings:
                    content: >
                        <h3>Админ панель <big>Tinkoff Store</big></h3>
            -
                class: col-xs-6
                position: left
                type: sonata.admin.block.stats
                settings:
                    code: admin.product
                    icon: fa-mobile
                    text: Товаров
                    color: bg-green
            -
                class: col-xs-6
                position: center
                type: sonata.admin.block.stats
                settings:
                    code: admin.variant
                    icon: fa-barcode
                    text: Моделей
                    color: bg-yellow
            -
                class: col-xs-6
                position: right
                type: sonata.admin.block.stats
                settings:
                    code: admin.manufacturer
                    icon: fa-building
                    text: Производителей
                    color: bg-red
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [admin.group.catalog]
            -
                position: center
                type: sonata.admin.block.admin_list
                settings:
                    groups: [admin.group.book]
        groups:
            admin.group.catalog:
                label: Каталог
                label_catalogue: AppBundle
                items:
                    - admin.product
                    - admin.variant
            admin.group.book:
                label: Справочники
                label_catalogue: AppBundle
                items:
                    - admin.manufacturer
                    - admin.attribute
                    - admin.attribute_group
            admin.group.relations:
                label: Вспомогательные сущности
                label_catalogue: AppBundle
                items:
                    # скрываем ассоциативные сущности т.к. их не нужно редактировать напрямую
                    #- admin.product_attribute
                    #- admin.variant_attribute
